### PR TITLE
Added basic draft for the topic of error checking

### PR DESCRIPTION
**Pull request by Connor-OShea**
Just a basic draft to get the groundwork of the topic done. I know you are good with words so feel free to play around with the explanations and examples :)

### CODE REVIEW

**Comment by DarkPurple141** [comment]
Will have a look shortly.

**Comment by DarkPurple141** [comment]
See latest changes. @COS97

**Review by DarkPurple141 — COMMENTED** [review]
Added some text, tried not to change too much. A few typos, formatting things. Otherwise good stuff. Let me know if you're happy and I'll approve the pr.

**Comment by 3N1GMA-HPY** [comment]
looks good :)
only bit I might add is:
"And, if you can, try to compile with dcc over gcc -- if you have it available. dcc picks up on a few extra issues that may cause issues, that gcc will happily overlook. If you only have gcc available, then compile using: gcc -Wall -Werror "

**Review by hpy — APPROVED** [review]
looks good :)
only bit I might add is:
"And, if you can, try to compile with dcc over gcc -- if you have it available. dcc picks up on a few extra issues that may cause issues, that gcc will happily overlook. If you only have gcc available, then compile using: gcc -Wall -Werror "

**Review by DarkPurple141 — APPROVED** [review]
Added K's feedback.

**Review by hpy — COMMENTED** [review]
looks great

**Pull request merged**
